### ISSUE TITLE
vim - requires pynvim and msgpack

### ISSUE THREAD

**Issue by Notgnoshi** [Notgnoshi/dotfiles#51]
#50 Fixed many completion problems, but added a new one. Deoplete requires pynvim and msgpack installed, and doesn't play well with virtualenvs -- requiring them to be installed _in_ the virtualenv.

- [ ] Make deoplete work well with virtualenvs
- [ ] Automatically install/update pynvim and msgpack on startup? Or perhaps just disable deoplete if they're not found.

**Comment by ndon55555** [comment]
Hi, was just running into the problem of pynvim not being available when I was in a virtual env and encountered this issue. Came back to say this helped me fix the problem with pynvim: https://neovim.io/doc/user/provider.html. Setting `g:python3_host_prog` to the path of my system python3 made deoplete not complain anymore. I don't know anything about msgpack, though. Hope this helps!

**Comment by Notgnoshi** [comment]
Setting `g:python3_host_prog` only works for neovim, not vanilla vim 8.1 :broken_heart:. You can set the python3 interpreter in vanilla vim by setting `pythonthreedll` and `pythonthreehome`, but that only works if vim was compiled with the `+python3/dyn` feature.

It might be possible to set `$PYTHONHOME` in my vimrc, but for now I think it's acceptable to install pynvim and msgpack in any virtualenv I work in (or use `--system-site-packages` and some discipline in my virtualenvs).

**Comment by ndon55555** [comment]
I'm also using Vim, not Neovim, but the variable still worked for me. I'm guessing when you say "vanilla" Vim, you'd be opposed to getting the nvim-yarp and vim-hug-neovim-rpc plugins that https://github.com/Shougo/deoplete.nvim says to get if you're using Vim? I don't 100% understand what they do, but I'm assuming they help shim a local Vim with a python Neovim.

**Comment by Notgnoshi** [comment]
...Interesting. I had nvim-yarp and vim-hug-neovim-rpc installed, and the required msgpack and pynvim python packages installed in `~/.local/lib/python3.8/`.

* Installing msgpack and pynvim in a virtualenv and setting `g:python3_host_prog = /path/to/virtualenv/bin/python3` didn't work
* Installing msgpack and pynvim in `~/.local/lib/python3.8/` and setting `g:python3_host_prog = '/usr/bin/python3'` didn't work either.
* Maybe I should try installing to the system python3.8?

But I don't actually need deoplete. ALE's auto completion is sufficient now that I've figured out how to use clangd as a language server with an embedded g++ toolchain. So I think I should avoid making my vim setup as complicated as possible and avoid deoplete.
